# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  MYSQL_HOST:${{ mysqlaws.MYSQL_HOST }}
  MYSQL_USER:${{ mysqlaws.MYSQL_USER }}
  MYSQL_PASSWORD:${{ mysqlaws.MYSQL_PASSWORD }}
  MYSQL_DB_NAME=${{ mysqlaws.MYSQL_DB_NAME }}
  MYSQL_PORT:${{ mysqlaws.MYSQL_PORT }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "Deploying to production server on branch $MYSQL_PASSWORD"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- student
